/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as V2RouteImport } from './routes/v2'
import { Route as TbdRouteImport } from './routes/tbd'
import { Route as CommunicateRouteImport } from './routes/communicate'
import { Route as IndexRouteImport } from './routes/index'

const V2Route = V2RouteImport.update({
  id: '/v2',
  path: '/v2',
  getParentRoute: () => rootRouteImport,
} as any)
const TbdRoute = TbdRouteImport.update({
  id: '/tbd',
  path: '/tbd',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunicateRoute = CommunicateRouteImport.update({
  id: '/communicate',
  path: '/communicate',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/communicate': typeof CommunicateRoute
  '/tbd': typeof TbdRoute
  '/v2': typeof V2Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/communicate': typeof CommunicateRoute
  '/tbd': typeof TbdRoute
  '/v2': typeof V2Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/communicate': typeof CommunicateRoute
  '/tbd': typeof TbdRoute
  '/v2': typeof V2Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/communicate' | '/tbd' | '/v2'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/communicate' | '/tbd' | '/v2'
  id: '__root__' | '/' | '/communicate' | '/tbd' | '/v2'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommunicateRoute: typeof CommunicateRoute
  TbdRoute: typeof TbdRoute
  V2Route: typeof V2Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/v2': {
      id: '/v2'
      path: '/v2'
      fullPath: '/v2'
      preLoaderRoute: typeof V2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tbd': {
      id: '/tbd'
      path: '/tbd'
      fullPath: '/tbd'
      preLoaderRoute: typeof TbdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communicate': {
      id: '/communicate'
      path: '/communicate'
      fullPath: '/communicate'
      preLoaderRoute: typeof CommunicateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommunicateRoute: CommunicateRoute,
  TbdRoute: TbdRoute,
  V2Route: V2Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
