/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as V2RouteImport } from './routes/v2'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as TbdRouteImport } from './routes/tbd'
import { Route as SalesforceRouteImport } from './routes/salesforce'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OopsRouteImport } from './routes/oops'
import { Route as MicrosoftTeamsRouteImport } from './routes/microsoft-teams'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as CommunicateRouteImport } from './routes/communicate'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as CaptureRouteImport } from './routes/capture'
import { Route as BookDemoRouteImport } from './routes/book-demo'
import { Route as AutomotiveRouteImport } from './routes/automotive'
import { Route as AppliedEpicRouteImport } from './routes/applied-epic'
import { Route as AccessibilityPlanRouteImport } from './routes/accessibility-plan'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as IndexRouteImport } from './routes/index'

const V2Route = V2RouteImport.update({
  id: '/v2',
  path: '/v2',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const TbdRoute = TbdRouteImport.update({
  id: '/tbd',
  path: '/tbd',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesforceRoute = SalesforceRouteImport.update({
  id: '/salesforce',
  path: '/salesforce',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OopsRoute = OopsRouteImport.update({
  id: '/oops',
  path: '/oops',
  getParentRoute: () => rootRouteImport,
} as any)
const MicrosoftTeamsRoute = MicrosoftTeamsRouteImport.update({
  id: '/microsoft-teams',
  path: '/microsoft-teams',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunicateRoute = CommunicateRouteImport.update({
  id: '/communicate',
  path: '/communicate',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptureRoute = CaptureRouteImport.update({
  id: '/capture',
  path: '/capture',
  getParentRoute: () => rootRouteImport,
} as any)
const BookDemoRoute = BookDemoRouteImport.update({
  id: '/book-demo',
  path: '/book-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomotiveRoute = AutomotiveRouteImport.update({
  id: '/automotive',
  path: '/automotive',
  getParentRoute: () => rootRouteImport,
} as any)
const AppliedEpicRoute = AppliedEpicRouteImport.update({
  id: '/applied-epic',
  path: '/applied-epic',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityPlanRoute = AccessibilityPlanRouteImport.update({
  id: '/accessibility-plan',
  path: '/accessibility-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/accessibility-plan': typeof AccessibilityPlanRoute
  '/applied-epic': typeof AppliedEpicRoute
  '/automotive': typeof AutomotiveRoute
  '/book-demo': typeof BookDemoRoute
  '/capture': typeof CaptureRoute
  '/coach': typeof CoachRoute
  '/communicate': typeof CommunicateRoute
  '/contact-us': typeof ContactUsRoute
  '/microsoft-teams': typeof MicrosoftTeamsRoute
  '/oops': typeof OopsRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/salesforce': typeof SalesforceRoute
  '/tbd': typeof TbdRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/thank-you': typeof ThankYouRoute
  '/v2': typeof V2Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/accessibility-plan': typeof AccessibilityPlanRoute
  '/applied-epic': typeof AppliedEpicRoute
  '/automotive': typeof AutomotiveRoute
  '/book-demo': typeof BookDemoRoute
  '/capture': typeof CaptureRoute
  '/coach': typeof CoachRoute
  '/communicate': typeof CommunicateRoute
  '/contact-us': typeof ContactUsRoute
  '/microsoft-teams': typeof MicrosoftTeamsRoute
  '/oops': typeof OopsRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/salesforce': typeof SalesforceRoute
  '/tbd': typeof TbdRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/thank-you': typeof ThankYouRoute
  '/v2': typeof V2Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/accessibility-plan': typeof AccessibilityPlanRoute
  '/applied-epic': typeof AppliedEpicRoute
  '/automotive': typeof AutomotiveRoute
  '/book-demo': typeof BookDemoRoute
  '/capture': typeof CaptureRoute
  '/coach': typeof CoachRoute
  '/communicate': typeof CommunicateRoute
  '/contact-us': typeof ContactUsRoute
  '/microsoft-teams': typeof MicrosoftTeamsRoute
  '/oops': typeof OopsRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/salesforce': typeof SalesforceRoute
  '/tbd': typeof TbdRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/thank-you': typeof ThankYouRoute
  '/v2': typeof V2Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/accessibility-plan'
    | '/applied-epic'
    | '/automotive'
    | '/book-demo'
    | '/capture'
    | '/coach'
    | '/communicate'
    | '/contact-us'
    | '/microsoft-teams'
    | '/oops'
    | '/pricing'
    | '/privacy-policy'
    | '/salesforce'
    | '/tbd'
    | '/terms-and-conditions'
    | '/thank-you'
    | '/v2'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/accessibility-plan'
    | '/applied-epic'
    | '/automotive'
    | '/book-demo'
    | '/capture'
    | '/coach'
    | '/communicate'
    | '/contact-us'
    | '/microsoft-teams'
    | '/oops'
    | '/pricing'
    | '/privacy-policy'
    | '/salesforce'
    | '/tbd'
    | '/terms-and-conditions'
    | '/thank-you'
    | '/v2'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/accessibility-plan'
    | '/applied-epic'
    | '/automotive'
    | '/book-demo'
    | '/capture'
    | '/coach'
    | '/communicate'
    | '/contact-us'
    | '/microsoft-teams'
    | '/oops'
    | '/pricing'
    | '/privacy-policy'
    | '/salesforce'
    | '/tbd'
    | '/terms-and-conditions'
    | '/thank-you'
    | '/v2'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  AccessibilityPlanRoute: typeof AccessibilityPlanRoute
  AppliedEpicRoute: typeof AppliedEpicRoute
  AutomotiveRoute: typeof AutomotiveRoute
  BookDemoRoute: typeof BookDemoRoute
  CaptureRoute: typeof CaptureRoute
  CoachRoute: typeof CoachRoute
  CommunicateRoute: typeof CommunicateRoute
  ContactUsRoute: typeof ContactUsRoute
  MicrosoftTeamsRoute: typeof MicrosoftTeamsRoute
  OopsRoute: typeof OopsRoute
  PricingRoute: typeof PricingRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SalesforceRoute: typeof SalesforceRoute
  TbdRoute: typeof TbdRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  ThankYouRoute: typeof ThankYouRoute
  V2Route: typeof V2Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/v2': {
      id: '/v2'
      path: '/v2'
      fullPath: '/v2'
      preLoaderRoute: typeof V2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tbd': {
      id: '/tbd'
      path: '/tbd'
      fullPath: '/tbd'
      preLoaderRoute: typeof TbdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salesforce': {
      id: '/salesforce'
      path: '/salesforce'
      fullPath: '/salesforce'
      preLoaderRoute: typeof SalesforceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oops': {
      id: '/oops'
      path: '/oops'
      fullPath: '/oops'
      preLoaderRoute: typeof OopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/microsoft-teams': {
      id: '/microsoft-teams'
      path: '/microsoft-teams'
      fullPath: '/microsoft-teams'
      preLoaderRoute: typeof MicrosoftTeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communicate': {
      id: '/communicate'
      path: '/communicate'
      fullPath: '/communicate'
      preLoaderRoute: typeof CommunicateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capture': {
      id: '/capture'
      path: '/capture'
      fullPath: '/capture'
      preLoaderRoute: typeof CaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-demo': {
      id: '/book-demo'
      path: '/book-demo'
      fullPath: '/book-demo'
      preLoaderRoute: typeof BookDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automotive': {
      id: '/automotive'
      path: '/automotive'
      fullPath: '/automotive'
      preLoaderRoute: typeof AutomotiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applied-epic': {
      id: '/applied-epic'
      path: '/applied-epic'
      fullPath: '/applied-epic'
      preLoaderRoute: typeof AppliedEpicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility-plan': {
      id: '/accessibility-plan'
      path: '/accessibility-plan'
      fullPath: '/accessibility-plan'
      preLoaderRoute: typeof AccessibilityPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  AccessibilityPlanRoute: AccessibilityPlanRoute,
  AppliedEpicRoute: AppliedEpicRoute,
  AutomotiveRoute: AutomotiveRoute,
  BookDemoRoute: BookDemoRoute,
  CaptureRoute: CaptureRoute,
  CoachRoute: CoachRoute,
  CommunicateRoute: CommunicateRoute,
  ContactUsRoute: ContactUsRoute,
  MicrosoftTeamsRoute: MicrosoftTeamsRoute,
  OopsRoute: OopsRoute,
  PricingRoute: PricingRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SalesforceRoute: SalesforceRoute,
  TbdRoute: TbdRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  ThankYouRoute: ThankYouRoute,
  V2Route: V2Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
